### ISSUE TITLE
Useful feedback

### ISSUE THREAD

**Issue by Slotkenov** [Slotkenov/javascript-examiner#14]

**Comment by Oizor** [comment]
@RonaldKluft Currently @Master: It does log something in check-*-feedback in the form 'String';'String', it thought this would be JSON, so we would be able to parse it and check if the key (= error) exists and whether it has a value (= translation) ? Or is this still to be merged?

Furthermore, there is no feedback output in de browser anymore. It only shows: 'line: column:'.

**Comment by RonaldKluft** [comment]
@Oizor I thought this was the way we would store this. Will check now how to save as JSON. Fixed the feedback. Should be working now. Forgot to implement the callback.

**Comment by Oizor** [comment]
@RonaldKluft while refactoring `check-format.js` I noticed a flaw with your feedback-mapper implementation. As the mapper works async, it's impossible to be sure wether the callback is executed before the `feedbacklist` is returned. As a result, the `feedbacklist` might be incomplete. There are several possibilities to overcome this:
* Use recursion in the checkFormat, (refactor whole forEach block in check-format)
* Call mapper after initial feedback has been created (after the forEach loop) and call initial callback within the callback of the mapper call. (refactor mapper)
* Sync mapper (this blocks, so I think this should be avoided.

**Comment by RonaldKluft** [comment]
@Oizor and @Slotkenov Checked in the mapper. Works well locally, but I dont receive a description from the check. Will look into this. Also will look into possibility to use parameter to set which field to use in mapper. Flaw is also still under investigation.
