### ISSUE TITLE
Logical data model

### ISSUE THREAD

**Issue by Slotkenov** [Slotkenov/javascript-examiner#15]

**Comment by Oizor** [comment]
Made some progress: we could use mongoose to define the structure of our documents (like solutions, feedback, testsuite), so we can maintain data integrity. Functionality to save and retrieve exercises has been added already. Start to work on the other documents this weekend. Will draw the model simultaneously. This issue should be fixed next Wednesday at latest.

**Comment by Oizor** [comment]
Follow up:
-Create fixtures to add initial exercises
-Draw model

**Comment by Oizor** [comment]
Extended Excercise object: [Data model](https://drive.google.com/file/d/0B3cPeZ3WjY2ZeDYzR3daMWRBMTQ/view?usp=sharing)

**Comment by Oizor** [comment]
Extended Params object, Added User document: [Data model](https://drive.google.com/file/d/0B3cPeZ3WjY2ZeDYzR3daMWRBMTQ/view?usp=sharing)

**Comment by Oizor** [comment]
Added solution to datamodel
