### ISSUE TITLE
Exercise management

### ISSUE THREAD

**Issue by Slotkenov** [Slotkenov/javascript-examiner#17]
Administration page for the tutor

**Comment by Oizor** [comment]
@Slotkenov @RonaldKluft As mentioned I won't be available tomorrow morning to prepare the demo. To get you up to date: Exercise management is added to the master branch. It's now possible to perform crud operations on exercises. To do so hit the 'Add' button or click on the pencil next to an exercise @/exercises . In case any difficulties show up tomorrow morning, contact me through Whatsapp. I will be available at 13:00 hrs at latest, and will call in on hangouts by then.
