### ISSUE TITLE
Feedback presentation

### ISSUE THREAD

**Issue by Slotkenov** [Slotkenov/javascript-examiner#19]

**Comment by Slotkenov** [comment]
Improved the presentation of feedback in the browser.

**Comment by Oizor** [comment]
@Slotkenov Is this improvement published already? Running code from master branch still shows former feedback presentation, as far I can tell. Or is the improvement very subtle? ^^

**Comment by Slotkenov** [comment]
@Oizor It has been published to master. The new feedback presentation should be visible.
Maybe you need to do an `npm install`? But it should give warnings otherwise.
What do you see at the moment?

**Comment by Oizor** [comment]
@Slotkenov never mind, forgot to run
> bower install.

**Comment by Oizor** [comment]
Looks awesome btw! :+1:
