### ISSUE TITLE
Research context paper

### ISSUE THREAD

**Issue by Oizor** [Slotkenov/javascript-examiner#2]
Also see article / thesis Hieke Keuning:
http://www.cs.uu.nl/research/techreps/UU-CS-2014-026.html
http://dspace.ou.nl/bitstream/1820/5388/1/INF_20140617_Keuning.pdf

**Comment by Oizor** [comment]
Also see:
A Review of Static Analysis Approaches for Programming Exercises
Striewe, Michael
Goedicke, Michael
2014
Programming assignments automatic grading review of tools and implementations
Caize et al.
2013
Review of recent systems for automatic assessment of programming assignments
Ihantola et al.
2010
Automatic programming assessment and test data generation a review on its approaches
Romli
2010
A Survey of Automated Assessment Approaches for Programming Assignments
Ala-Mutka
2005
Automatic test-based assessment of programming: A review
Douce
2005

**Comment by Oizor** [comment]
Finished the introduction. Started to work on a resume of the consult. Try to have this chapter + start of the SPV chapter ready on thursday.

**Comment by Oizor** [comment]
Finalized concept consult chapter.

**Comment by Oizor** [comment]
Finalized draft.
@Slotkenov and @RonaldKluft please modify and replenish. Some remarks:
- The document can be parsed with research-context-stand-alone.text in the main directory of the documentation branch
-There are some TODO's left (commented). 
-The styling needs some attention (did not focus on the Latex semantics)

**Comment by Oizor** [comment]
Draft version (v1.0) submitted and labeled.

**Comment by Slotkenov** [comment]
Great!
