### ISSUE TITLE
Overview of exercises

### ISSUE THREAD

**Issue by Slotkenov** [Slotkenov/javascript-examiner#20]

**Comment by Oizor** [comment]
@Slotkenov What is the status of the front-end? Can we demo this upcoming Thursday? If not, what work has to be done? I might have some time left on Wednesday to work on this.

**Comment by Slotkenov** [comment]
@Oizor I have been reading up on Polymer, but haven't implemented anything yet. I am trying to work on it Tuesday and Wednesday. If you have time to help on Wednesday, that would be great.

**Comment by Oizor** [comment]
@Slotkenov Unfortunately I am not able to work on this issue tonight. If it's not finished, we might have some time left tomorrow morning to fix the view.
