### ISSUE TITLE
Refactor database.js

### ISSUE THREAD

**Issue by Oizor** [Slotkenov/javascript-examiner#42]

**Comment by RonaldKluft** [comment]
@Oizor I'm not sure my fix is OK, want to show code

**Comment by Oizor** [comment]
Fixed in commit 58f14a1

**Comment by Oizor** [comment]
Reverted because it does insert same documents twice.

**Comment by RonaldKluft** [comment]
@Oizor and @Slotkenov : Updated return value in gh-42 in commit 78b76bb
