### ISSUE TITLE
Deploy javascript-examiner @ demo environment

### ISSUE THREAD

**Issue by Oizor** [Slotkenov/javascript-examiner#49]

**Comment by Slotkenov** [comment]
The Javascript Examiner is now live at:
https://javascript-examiner.herokuapp.com

Deployment to heroku needs to go through me.

7c94776
f3544a7
f7c3881
954d417
ae17432
a12ae67
1b6f650
01ed0b2
7d7c0fe
1b031ea
5ad47b7
