### ISSUE TITLE
Unit testing of our own code

### ISSUE THREAD

**Issue by Slotkenov** [Slotkenov/javascript-examiner#6]
Setup an environment that allows us to create unit tests for our own code.
Make running those unit tests, as well as checking the formatting of our code, an automated process.

**Comment by RonaldKluft** [comment]
Een nieuwe branch unittest gemaakt.

**Comment by Oizor** [comment]
@RonaldKluft is it possible to:
-write 1 gulp task that refers to all files in the test directory instead of creating a separate task for each test?
-currently based on master: after changing a file and saving it, it does not seem to run the tests again.
