### ISSUE TITLE
Reviewing and Refactoring

### ISSUE THREAD

**Issue by Oizor** [Slotkenov/javascript-examiner#67]

**Comment by Oizor** [comment]
Current structure does not suffice when looking at the contents of the thesis. For example research is now structured as followed:

* Research
  * Domain research
    * Introduction
  * Paper 1
  * Paper 2
  * Paper 3

But it should be like:

* Research
  * Domain research
    * Introduction
    * Paper 1
    * Paper 2
    * Paper 3
Maybe it's more convenient to make the Domain Research and Research context to separate ``parts``, because in this way the amount of refactoring is minimised. Another approach is to only link to the articles in our thesis and add them as appendices.

**Comment by Slotkenov** [comment]
Including the domain research articles as attachments seems a nice approach.
As I understand it we each only need to include or own paper though, right?
