### ISSUE TITLE
Manage presentation preperation

### ISSUE THREAD

**Issue by Oizor** [Slotkenov/javascript-examiner#68]

**Comment by Oizor** [comment]
Three perspectives:
- Tutor
  * Reduce labor intensity
  * Facilitate students
  * Monitor student progress
  * Examine students
  * Manage course material
- Student
  * Learn JavaScript
  * Know where to improve (accurate feedback)
  * Stimulating environment
  * Interaction with tutor / other students
  * Pass the exam
- Researcher
  * What makes good feedback
  * Analyse learning process
  * Usage statistics
  * Analyse accuracy feedback
  * Reason about the properties of good code
  * Determine which configuration leads to the best performative learning environment

**Comment by Slotkenov** [comment]
I love the idea of this thematic approach!
